#include "main.h"
#include "adc.h"
#include "usart.h"

void SystemClock_Config(void);
void Error_Handler(void);
static void MX_GPIO_Init(void);

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_ADC1_Init();
    MX_ADC3_Init();
    MX_USART2_UART_Init();

    uint32_t adcValue = 0;
    float voltage = 0.0;

    while (1)
    {
        // Start ADC conversion
        HAL_ADC_Start(&hadc1);

        // Wait for conversion to finish
        if (HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY) == HAL_OK)
        {
            // Get the ADC value
            adcValue = HAL_ADC_GetValue(&hadc1);

            // Convert the ADC value to voltage
            voltage = ((float)adcValue / 255.0) * 3.3;

            // Print ADC value and voltage over UART
            char msg[50];
            sprintf(msg, "ADC Value: %lu, Voltage: %.2fV\r\n", adcValue, voltage);
            HAL_UART_Transmit(&huart2, (uint8_t*)msg, strlen(msg), HAL_MAX_DELAY);
        }

        // Stop ADC conversion
        HAL_ADC_Stop(&hadc1);

        // Delay for a bit
        HAL_Delay(1000);
    }
}

void SystemClock_Config(void)
{
    // System Clock Configuration code (generated by CubeMX)
}

static void MX_GPIO_Init(void)
{
    // GPIO Initialization code (generated by CubeMX)
}
